// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq1CdeiR0ItUk7n3i4YLVDAMzARokvbjw',
    appId: '1:956282452798:web:ec714b1d8455de3cb70a6f',
    messagingSenderId: '956282452798',
    projectId: 'majorizer-nprts',
    authDomain: 'majorizer-nprts.firebaseapp.com',
    storageBucket: 'majorizer-nprts.appspot.com',
    measurementId: 'G-8TTVZ0XEQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7tB1kUmxS3Lx5U5XA6qeWdjvyKeOeiRI',
    appId: '1:956282452798:android:64475c7a6a1414ecb70a6f',
    messagingSenderId: '956282452798',
    projectId: 'majorizer-nprts',
    storageBucket: 'majorizer-nprts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD519iQbB_cI793vGGnw9koBHwwE73nOao',
    appId: '1:956282452798:ios:a0c0e6b12dcc07b1b70a6f',
    messagingSenderId: '956282452798',
    projectId: 'majorizer-nprts',
    storageBucket: 'majorizer-nprts.appspot.com',
    iosClientId: '956282452798-ptbf39oesgl3lrkc88m7s3eoqrda7bko.apps.googleusercontent.com',
    iosBundleId: 'com.example.majorizerUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD519iQbB_cI793vGGnw9koBHwwE73nOao',
    appId: '1:956282452798:ios:a0c0e6b12dcc07b1b70a6f',
    messagingSenderId: '956282452798',
    projectId: 'majorizer-nprts',
    storageBucket: 'majorizer-nprts.appspot.com',
    iosClientId: '956282452798-ptbf39oesgl3lrkc88m7s3eoqrda7bko.apps.googleusercontent.com',
    iosBundleId: 'com.example.majorizerUi',
  );
}
